[package]
name = "zune"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0 OR Zlib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    # Core functionality
    "zune-core",
    # Main struct
    "zune-image",
    # CLI app
    "zune-bin",
    # Image processing routines.
    "zune-imageprocs",
    # Image formats
    "zune-farbfeld",
    "zune-jpeg",
    "zune-jpegxl",
    "zune-ppm",
    "zune-png",
    "zune-psd",
    "zune-qoi",
    # additional stuff
    "zune-inflate",
    #testing
    "zune-tests",
    # Benchmarking
    "zune-benches",
    # WASM
    "zune-wasm"

]

[dependencies]
zune-bin = { path = "./zune-bin" }

[profile.release]
debug = 2

[profile.bench]
debug = true
