[package]
name = "zune-core"
version = "0.2.12"
edition = "2021"
description = "Core utilities for image processing in the zune family of crates"
exclude = ["tests/"]
homepage = "https://github.com/etemesi254/zune-image/tree/dev/zune-core"
keywords = ["image"]
categories = ["multimedia::images", "multimedia::encoding"]
license = "MIT OR Apache-2.0 or Zlib"

[features]
# When present, we can use std facilities to detect
# if a specific feature exists
std = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
default = ["serde"]
[dependencies]
bitflags = "2.0.2"
serde = { version = "1.0.52", optional = true }